name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gerar Gradle Wrapper
        run: |
          cd android
          gradle wrapper

      - name: Enviar arquivos para o repositório
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add android/gradlew android/gradlew.bat android/gradle/wrapper
          git commit -m "Adicionar Gradle Wrapper"
          git push
